
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";

import type { Metadata } from "next";

import { RootProvider } from "../app/components/createContext";
import Navbar from "./components/Navigation/Navbar";
import Footer2 from "./components/Footer/Footer";




const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Rezoom AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <RootProvider>
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="font-sans">
        <Navbar />
        <div className="w-full min-h-screen">
        {children}
        </div>
        <Footer2 />
      </body>
    </html>
    </RootProvider>
  );
}
