
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";

import type { Metadata } from "next";
import Navbar from "./Components/Navigation/Navbar";
import Footer from "./Components/Footer/Footer";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Rezoom AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="w-11/12 mx-auto space-y-5 font-sans">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
